### ISSUE TITLE
When attempting to start script, id get this error

### ISSUE THREAD

**Issue by ZacerLivo** [TFNRP/seatbelt#19] opened 2023-12-12 13:44 UTC
![image](https://github.com/TFNRP/seatbelt/assets/153625048/dfae6343-9752-4e2f-a551-1505898f465b)

Unsure how to fix, any insight would be greatly appreciated!

**Comment by MrGriefs** [comment] 2023-12-12 13:46
Duplicate of #14

**Closed as not planned by MrGriefs** 2023-12-12 13:46 UTC
Labels: duplicate
