### ISSUE TITLE
Yarn Issue

### ISSUE THREAD

**Issue by P4R4NORM4L** [TFNRP/seatbelt#20] opened 2023-12-13 03:06 UTC
Couldn't start resource seatbelt
[         script:yarn] [yarn]	yarn install v1.22.5
[         script:yarn] [yarn]	[1/4] Resolving packages...
[         script:yarn] [yarn]	[2/4] Fetching packages...
[         script:yarn] Error: [yarn]	error execa@7.2.0: The engine "node" is incompatible with this module. Expected version "4.18.0 || 6.14.0 || >=18.0.0". Got "16.9.1"
[         script:yarn] Error: [yarn]	error Found incompatible module.

Tried these commands:
yarn upgrade
yarn install

no luck

**Comment by MrGriefs** [comment] 2023-12-13 08:37
Duplicate of #14

**Closed as not planned by MrGriefs** 2023-12-13 08:37 UTC
Labels: duplicate
