### ISSUE TITLE
error when installing seatbelt

### ISSUE THREAD

**Issue by FreZaMartin** [TFNRP/seatbelt#18] opened 2023-12-06 18:34 UTC
When I start the server I get an error saying
![image_2023-12-06_193438472](https://github.com/TFNRP/seatbelt/assets/84147658/613a4773-7aeb-452c-9984-877405df12c0)

**Comment by MrGriefs** [comment] 2023-12-06 18:47
Duplicate of #14

**Closed by MrGriefs** 2023-12-06 18:47 UTC
