### ISSUE TITLE
Does not start

### ISSUE THREAD

**Issue by SiahRBLX** [TFNRP/seatbelt#15] opened 2023-09-10 17:51 UTC
> ensure "seatbelt"
[ citizen-server-impl] Running build tasks on resource seatbelt - it'll restart once completed.
[ citizen-server-impl] Couldn't start resource seatbelt.
[         script:yarn] [yarn]	yarn install v1.22.5
[         script:yarn] [yarn]	[1/4] Resolving packages...
> txaReportResources
[      script:monitor] [txAdmin] Sending resources list to txAdmin.
[         script:yarn] [yarn]	[2/4] Fetching packages...
[         script:yarn] Error: [yarn]	error execa@7.2.0: The engine "node" is incompatible with this module. Expected version "4.18.0 || 6.14.0 || >=18.0.0". Got "16.9.1"
[         script:yarn] Error: [yarn]	error Found incompatible module.
[         script:yarn] [yarn]	info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[ citizen-server-impl] Building resource seatbelt failed.
[ citizen-server-impl] Error data: yarn failed!

**Comment by MrGriefs** [comment] 2023-09-10 17:57
Duplicate of #14

**Closed as not planned** 2023-09-10 17:57 UTC
Labels: duplicate
